#index:
#    path: /
#    controller: App\Controller\DefaultController::index
post_usuario:
    path: /teste
    controller: 'App\Controller\TesteController::index'
    methods: [POST, GET]
    defaults:
        _format: html
post_login:
    path: /auth
    controller: 'App\Controller\TesteController::auth'
    methods: [POST]
    
home:
    path: /home
    controller: 'App\Controller\TesteController::home'
    methods: [GET]
        