login:
    path: /login
    controller: 'App\Controller\TesteController::login'
    methods: [POST, GET]
    defaults:
        _format: html
logout:
    path: /logout
    controller: 'App\Controller\TesteController::logout'
    methods: [POST, GET]
    defaults:
        _format: html
auth:
    path: /auth
    controller: 'App\Controller\TesteController::auth'
    methods: [POST]
    
home:
    path: /home
    controller: 'App\Controller\TesteController::home'
    methods: [GET]
        